name: tradeasy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  open_file: ^3.0.1
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.17


  file_picker: ^6.1.1
  excel: ^4.0.2
  email_validator: '^2.1.16'


  cupertino_icons: ^1.0.2
  excel_dart: ^3.0.0
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./Assets/Logo.png"

  flutter_lints: ^3.0.1


flutter:
 
  uses-material-design: true

